vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        menu_pictures:
            uri_prefix: /media
            upload_destination: '%kernel.project_dir%/public/media'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
